### ISSUE TITLE
Balance Table: Python

### ISSUE THREAD

**Issue by mcwayrm** [NickCH-K/LOST#1]
Need to add the `python` code for creating a balance table

**Comment by mcwayrm** [comment]
Additionally, I could not find a good source to explain balance tables. If anyone finds one please replace my placeholder for a wikipedia page on balance tables

**Comment by NickCH-K** [comment]
Wikipedia seems fine to me! The link does need a url though. I tried to add it but couldn't find which page you were trying to link to.

**Comment by mcwayrm** [comment]
@NickCH-K  Sorry if I was unclear. The wikipedia link is a placeholder for if we find something. I couldn't find anything for balance tables on wikipedia and no good alternative for a general explanation.
