### ISSUE TITLE
Where to categorize power calc and the like?

### ISSUE THREAD

**Issue by mcwayrm** [NickCH-K/LOST#2]
I was wondering if power calcs and simulated dataframs warranted their own category `pre-analysis` or if they should be fit in somewhere else?

Similar topics in this realm of pre-analysis (in my view) are importing different types of data, data cleaning, handling missing values, merging dataframes, etc. ...

**Comment by NickCH-K** [comment]
Hmm, good question. Pre-analysis might make sense. But I wonder if it might make sense to make it a category of techniques about evaluating an analysis generally, so that robustness check-type stuff would go in. Not sure of a snappy name to call it though.
